include:
  - name: corne_left_display # Левая половина с экраном
    board: nice_nano@2/nrf52840/zmk
    shield: corne_left
  - name: corne_right_display # Правая половина с экраном
    board: nice_nano@2/nrf52840/zmk
    shield: corne_right
