manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: mctechnology17
      url-base: https://github.com/mctechnology17
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v3.7.0 # ← заменили main на тег релиза
      import: app/west.yml
    - name: zmk-oled-adapter # если используете
      remote: mctechnology17
      revision: main # или тоже зафиксируйте, если есть теги
  self:
    path: config
