name: Build ZMK Firmware
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache west modules
        uses: actions/cache@v4
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
            zmk/
          key: ${{ runner.os }}-zephyr-${{ hashFiles('config/west.yml') }}

      - name: West Init
        run: west init -l config

      - name: West Update
        run: west update

      - name: West Zephyr Export
        run: west zephyr-export

      - name: Build Left
        run: west build -s zmk/app -b nice_nano_v2 -- -DSHIELD=corne_left -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"
      - name: Rename Left
        run: cp build/zephyr/zmk.uf2 corne_left_nice_nano_v2.uf2

      - name: Build Right
        run: west build -s zmk/app -b nice_nano_v2 -- -DSHIELD=corne_right -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"
      - name: Rename Right
        run: cp build/zephyr/zmk.uf2 corne_right_nice_nano_v2.uf2

      - name: Archive
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: |
            corne_left_nice_nano_v2.uf2
            corne_right_nice_nano_v2.uf2
